<?php

require_once "includes/ABTestCommentTipsService.inc";

/**
 * Implements hook_smartparticipation_admin_settings_form_alter().
 */
function smartparticipation_ab_test_comment_tips_smartparticipation_admin_settings_form_alter(&$form)
{
  $ab_test_service = new \SmartParticipation\ABTestService;
  $ab_tests = $ab_test_service->getOptionsList();
  array_unshift($ab_tests, '-- no active test --');
  $form['comment_support_tips'][\SmartParticipation\ABTestCommentTipsService::ACTIVE_TEST_VAR_NAME] = array(
    '#title' => t('Active A/B Test'),
    '#type' => 'select',
    '#description' => 'The A/B test currently active for comment support tips.',
    '#options' => $ab_tests,
    '#default_value' => variable_get(\SmartParticipation\ABTestCommentTipsService::ACTIVE_TEST_VAR_NAME, ''),
    '#weight' => 10,
  );
}

/**
 * Implements hook_smartparticipation_topic_comment_tips_alter().
 */
function smartparticipation_ab_test_comment_tips_smartparticipation_topic_comment_tips_alter(&$comment_tips, $topic_context_data)
{
  $user = $topic_context_data['user'];
  $comment_tips_service = $topic_context_data['comment_tips_service'];
  $proposal_nid = $topic_context_data['proposal_nid'];
  $topic_phase_tid = $topic_context_data['topic_phase_tid'];
  $ab_test_service = new \SmartParticipation\ABTestCommentTipsService;
  if ($user && $comment_tips && $ab_test_service->userIsEligible($user)) {
    // Check for active comment tips A/B test
    if ($active_ab_test = $ab_test_service->getActiveABTest()) {
      // Check for an existing user variant for this test
      // Assign the user a variant if they don't have one
      if ($user) {
        $ab_test_user_variant_service = new \SmartParticipation\ABTestUserVariantService;
        $user_variant = $ab_test_user_variant_service->find($active_ab_test, $user);
        // Retrieve info about this test
        $ab_test_info = $ab_test_service->getTestInfo($user_variant, $comment_tips_service, $proposal_nid, $topic_phase_tid);
        // The user is assigned to a variant where comment tips are enabled
        if ($ab_test_service->showCommentTips($ab_test_info)) {
          // Is a second set of comment tips being used for this variant?
          // If so, replace the comment tips set above with the return value
          if ($variant_comment_tips = $ab_test_service->getVariantCommentTips($ab_test_info)) {
            $comment_tips = $variant_comment_tips;
          }
        }
        // Comment tips are disabled for this variant
        else {
          $comment_tips = NULL;
        }
      }
    }
  }
}