; This file was auto-generated by drush make
core = 7.x
api = 2

defaults[projects][subdir] = "contrib"

; Contrib modules
projects[advanced_help][version] = "1.1"

projects[ctools][version] = "1.10"

projects[conditional_styles][version] = "2.2"

projects[cnr][version] = "4.22"

projects[date][version] = "2.8"

projects[devel][version] = "1.5"

projects[diff][version] = "3.2"

projects[elements][version] = "1.4"

projects[entity][version] = "1.6"

projects[entityreference][version] = "1.1"

projects[entityreference_prepopulate][version] = "1.5"

projects[field_collection][version] = "1.0-beta7"

projects[media][version] = "1.4"

projects[flag][version] = "3.9"

projects[globalredirect][version] = "1.5"

projects[honeypot][version] = "1.17"

projects[html5_tools][version] = "1.2"

projects[hybridauth][version] = "2.15"

projects[imce][version] = "1.9"

projects[imce_wysiwyg][version] = "1.0"

projects[jquery_update][version] = "3.0-alpha2"

projects[libraries][version] = "2.2"

projects[logintoboggan][version] = "1.4"

projects[menu_node][version] = "1.2"

projects[menu_token][version] = "1.0-beta5"

projects[metatag][version] = "1.21"

projects[mmenu][version] = "2.1"

projects[nice_menus][version] = "2.5"

projects[references][version] = "2.1"

projects[pathauto][version] = "1.2"

projects[profanity][version] = "1.x-dev"

projects[role_delegation][version] = "1.1"

projects[smtp][version] = "1.0"

projects[special_menu_items][version] = "2.0"

projects[strongarm][version] = "2.0"

projects[subpathauto][version] = "1.3"

projects[taxonomy_display][version] = "1.1"

projects[token][version] = "1.5"

projects[webform][version] = "3.27"

projects[webform_conditional][version] = "1.0-beta2"

projects[webform_validation][version] = "1.10"

projects[weight][version] = "2.3"

projects[wysiwyg][version] = "2.x-dev"

projects[wysiwyg_linebreaks][version] = "1.6"

