<?php
/**
 * @file
 * Install, update and uninstall functions for the standard install profile.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function smartparticipation_install() {
  smartparticipation_core_set_default_smartparticipation_core_themes();
  //smartparticipation_core_set_default_themes('smartparticipation_default', 'smartparticipation_admin');
}