<?php

module_load_include('inc', 'smartparticipation_core', 'app/models/Model');
require_once "includes/ABTest.inc";
require_once "includes/ABTestUserVariant.inc";
require_once "includes/ABTestService.inc";
require_once "includes/ABTestUserVariantService.inc";

/**
 * Implements hook_menu().
 */
function smartparticipation_ab_test_menu()
{
  $items = array();

  $items['admin/config/system/ab_test'] = array(
    'title' => 'SmartParticipation A/B Test',
    'description' => 'Define A/B tests.',
    'page callback' => 'smartparticipation_ab_test_admin_list',
    'access arguments' => array('administer smartparticipation_core configuration'),
    'weight' => 1,
    'file' => 'smartparticipation_ab_test.admin.inc',
  );

  $items['admin/config/system/ab_test/add'] = array(
    'title' => 'Add A/B Test',
    'description' => 'Configure a new A/B test.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('smartparticipation_ab_test_admin_form'),
    'access arguments' => array('administer smartparticipation_core configuration'),
    'weight' => 2,
    'file' => 'smartparticipation_ab_test.admin.inc',
  );

  $items['admin/config/system/ab_test/%/edit'] = array(
    'title' => 'Edit A/B Test',
    'description' => 'Edit an A/B test.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('smartparticipation_ab_test_admin_form', 4),
    'access arguments' => array('administer smartparticipation_core configuration'),
    'weight' => 3,
    'file' => 'smartparticipation_ab_test.admin.inc',
  );

  $items['admin/config/system/ab_test/%/delete'] = array(
    'title' => 'Delete A/B Test',
    'description' => 'Delete an A/B test.',
    'page callback' => 'smartparticipation_ab_test_admin_delete',
    'page arguments' => array(4),
    'access arguments' => array('administer smartparticipation_core configuration'),
    'weight' => 4,
    'file' => 'smartparticipation_ab_test.admin.inc',
  );

  $items['node/%node/export-ab-test-descriptions'] = array(
    'page callback' => '_smartparticipation_export_ab_test_csv',
    'page arguments' => array(1),
    'access callback' => 'smartparticipation_core_access_check_export',
    'access arguments' => array(1),
    'file' => 'smartparticipation_ab_test.export.inc',
  );

  $items['node/%node/export-ab-test-assignments'] = array(
    'page callback' => '_smartparticipation_export_ab_test_assignments_csv',
    'page arguments' => array(1),
    'access callback' => 'smartparticipation_core_access_check_export',
    'access arguments' => array(1),
    'file' => 'smartparticipation_ab_test.export.inc',
  );

  return $items;
}

/**
 * Implements hook_smartparticipation_export_menu_items_alter().
 */
function smartparticipation_ab_test_smartparticipation_export_menu_items_alter(&$export_menu_items, $nid)
{
  $export_menu_items['A/B test descriptions'] = 'node/' . $nid . '/export-ab-test-descriptions';
  $export_menu_items['A/B test user assignments'] = 'node/' . $nid . '/export-ab-test-assignments';
}