<?php

/**
 * @file 
 * A module for custom SmartParticipation functionality.
 * 
 * @ingroup smartparticipation_core
 */

smartparticipation_core_require_files();

/**
 * Load the files required by the module.
 */
function smartparticipation_core_require_files() {
  $module_dir = drupal_get_path('module', 'smartparticipation_core');
  $files = array();
  $files += file_scan_directory($module_dir . '/entities', '/\.inc/');
  $files += file_scan_directory($module_dir . '/forms', '/\.inc/');
  $files += file_scan_directory($module_dir . '/includes', '/\.inc/', array('recurse' => false));
  $files += file_scan_directory($module_dir . '/node_types', '/\.inc/');
  $files += file_scan_directory($module_dir . '/taxonomy', '/\.inc/');

  foreach (array_keys($files) as $filename) {
    require_once $filename;
  }

  $models = array(
    'Model',
    'User',
    'Endorsement',
    'EventLogRecord',
    'AccessLogRecord',
    'ShowMoreCommentsResult',
  );

  array_map(
    function ($class_name) use ($module_dir) {
      require_once $module_dir . '/includes/models/' . $class_name . '.inc';
    },
    $models
  );

  $lib = array(
    'UserService',
    'EndorsementService',
    'UserHelper',
    'EventLogService',
    'AccessLogService',
    'PageService',
    'FeaturedCommentsService',
    'RecentCommentsService',
    'RecommendedCommentsService',
    'ShowMoreFeaturedComments',
    'ShowMoreFeaturedCommentsRequest',
    'ShowMoreRecentCommentsRequest',
    'ShowMoreRecommendedCommentsRequest',
  );

  array_map(
    function ($class_name) use ($module_dir) {
      require_once $module_dir . '/includes/lib/' . $class_name . '.inc';
    },
    $lib
  );

}

/**
 * Implements hook_help().
 */
function smartparticipation_core_help($path, $arg) {
  if ($path == 'admin/help#smartparticipation_core_core') {
    return t('Module for custom SmartParticipation functionality.');
  }
}


/**
 * Implements hook_init().
 */
function smartparticipation_core_init() {

  // Not on admin pages
  if (arg(0) != 'admin') {
    // Not an AJAX request
    if (empty($_SERVER['HTTP_X_REQUESTED_WITH']) || strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) !== 'xmlhttprequest') {

      smartparticipation_core_init_login_and_registration();
      smartparticipation_core_init_alert();
      smartparticipation_core_init_dialog();

      /*
       * This technique doesn't work due to Drupal page caching. The page is
       * cached with the custom variable set, so the results are not accurate.
       * smartparticipation_core_set_cookie_from_query_param();
       * smartparticipation_core_add_ga_custom_variables();
      */
    }
  }
}

